feat: metrics
caos/zitadel pull request #1024
Opened 2020-11-27 10:42 UTC by fgerschwiler

2020-11-30 08:00 UTC, livio-a requested changes

2020-11-30 08:00 UTC, livio-a commented on internal/admin/repository/eventsourcing/eventstore/administrator.go
> +	return divDuration.Nanoseconds()
not sure if we should stick with nanoseconds or if miliseconds would be enough

2020-11-30 08:24 UTC, fgerschwiler commented on internal/admin/repository/eventsourcing/handler/user_external_idps.go
> +	return spooler.HandleSuccess(i.view.UpdateExternalIDPSpoolerRunTimestamp)
its correct

2020-11-30 10:00 UTC, fgerschwiler commented on internal/api/grpc/errors/caos_errors.go
> -	}
Because OK code is also relevant

2020-11-30 12:12 UTC, fgerschwiler commented on internal/eventstore/spooler/spooler.go
>  	return nil
done

2020-11-30 12:18 UTC, fgerschwiler commented on internal/telemetry/metrics/otel/open_telemetry.go
> +		name, callbackFunc, metric.WithDescription(description), metric.WithInstrumentationName("test"))
this was just a test, I remove it

2020-11-30 12:19 UTC, fgerschwiler commented on internal/telemetry/metrics/otel/open_telemetry.go
> +	counter := metric.Must(m.Meter).NewInt64Counter(name, metric.WithDescription(description), metric.WithInstrumentationName("test"))
this was just a test, I remove it

2020-11-30 13:03 UTC, fgerschwiler commented on internal/telemetry/metrics/http_handler.go
> +		h.filters = append(h.filters, shouldNotIgnore(ignoredEndpoints...))
its copy from trace, i think its because, it filters if endpoint is ok

2020-11-30 13:38 UTC, fgerschwiler commented on internal/telemetry/metrics/otel/open_telemetry.go
> +	UpDownSumObserver map[string]metric.Int64UpDownSumObserver
changed to sync.Map

2020-12-02 07:50 UTC, livio-a approved these changes

2020-12-02 07:50 UTC, merged

2020-12-02 08:06 UTC, fforootd commented
:tada: This PR is included in version 0.107.0 :tada:

The release is available on [GitHub release](https://github.com/caos/zitadel/releases/tag/v0.107.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: