Nginx certmanager support impl
caos/zitadel pull request #1344
Opened 2021-02-25 09:54 UTC by eliobischof

2021-03-03 12:26 UTC, stebenz requested changes

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/controllers/ingress/adapt_test.go
> +	cover("NGINX")
Is there any coverage for the "any"-ingress?

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/protocol/adapt_test.go
> +/*
Cleanup necessary? Or is this commented part used later?

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/protocol/core/controller.go
> +type CORS mapping.CORS
Is this even necessary? Why not use the ambassador struct directly?

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/protocol/adapt_test.go
> +func TestAdaptFuncCover(t *testing.T) {
Tests with no content? There are no assertions, no mocking, and no use of the functions outside?
We shouldn't include tests that only cover the functions, they are more or less useless, either with assertions or delete altogether.

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/adapt_test.go
> +func TestAdaptFuncCover(t *testing.T) {
Tests with no content? There are no assertions, no mocking, and no use of the functions outside?
We shouldn't include tests that only cover the functions, they are more or less useless, either with assertions or delete altogether.

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/controllers/ingress/adapt_test.go
> +func TestAdaptFuncCover(t *testing.T) {
Tests with no content? There are no assertions, no mocking, and no use of the functions outside?
We shouldn't include tests that only cover the functions, they are more or less useless, either with assertions or delete altogether.

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/controllers/nginx/adapt_test.go
> +func TestAdaptFuncCover(t *testing.T) {
Tests with no content? There are no assertions, no mocking, and no use of the functions outside?
We shouldn't include tests that only cover the functions, they are more or less useless, either with assertions or delete altogether.

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/protocol/grpc/adapt_test.go
> +func TestAdaptFuncCover(t *testing.T) {
Tests with no content? There are no assertions, no mocking, and no use of the functions outside?
We shouldn't include tests that only cover the functions, they are more or less useless, either with assertions or delete altogether.

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/protocol/grpc/adapt_test.go
> +/*
Cleanup necessary? Or is this commented part used later?

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/protocol/ui/adapt_test.go
> +/*
Cleanup necessary? Or is this commented part used later?

2021-03-03 12:26 UTC, stebenz commented on operator/zitadel/kinds/iam/zitadel/ingress/protocol/ui/adapt_test.go
> +func TestAdaptFuncCover(t *testing.T) {
Tests with no content? There are no assertions, no mocking, and no use of the functions outside?
We shouldn't include tests that only cover the functions, they are more or less useless, either with assertions or delete altogether.

2021-03-03 12:26 UTC, stebenz commented on .github/workflows/operator.yml
> +name: Operator Release
Please merge back the master to include the pipeline changes as well otherwise, we could face some problems when releasing

2021-06-25 12:34 UTC, fforootd commented
do we still need this?

2021-09-23 08:21 UTC, closed without merging