fix(zitadelctl): implementation for commands in crd mode
caos/zitadel pull request #1685
Opened 2021-04-27 17:38 UTC by stebenz

2021-05-04 13:26 UTC, eliobischof requested changes

2021-05-04 13:26 UTC, eliobischof commented on operator/zitadel/kinds/orb/reconcile.go
>  	"github.com/caos/orbos/mntr"
```suggestion
	"fmt"

	"github.com/caos/orbos/mntr"
```

2021-05-04 13:26 UTC, eliobischof commented on operator/zitadel/kinds/orb/reconcile.go
> +				return err
```suggestion
				return errors.New("no version provided for self-reconciling")
```

2021-05-04 13:26 UTC, eliobischof commented on operator/zitadel/kinds/orb/reconcile.go
>  				return err
```suggestion
				return fmt.Errorf("failed to destroy zitadel-operator in k8s-cluster: %w", err)
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/backup.go
>  		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/backup.go
> +		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/backuplist.go
> +		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on operator/zitadel/kinds/orb/reconcile.go
> +				return err
```suggestion
				return errors.New("no version provided for self-reconciling")
```

2021-05-04 13:26 UTC, eliobischof commented on operator/zitadel/kinds/orb/reconcile.go
>  				return err
```suggestion
				return fmt.Errorf("failed to destroy zitadel-operator in k8s-cluster: %w", err)
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/backup.go
>  		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/backup.go
> +		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/backuplist.go
> +		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/backuplist.go
> +		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/backuplist.go
> +		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/clear.go
>  		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/clear.go
>  		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/restore.go
>  		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/databases/restore.go
> +		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/zitadel/migration.go
> +		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/zitadel/migration.go
> +		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/zitadel/zitadel.go
> +		monitor.Error(err)
```suggestion
```

2021-05-04 13:26 UTC, eliobischof commented on pkg/zitadel/zitadel.go
> +		monitor.Error(err)
```suggestion
```

2021-06-25 12:33 UTC, fforootd commented
is this still needed?

2021-07-16 13:13 UTC, eliobischof approved these changes

2021-07-20 12:30 UTC, eliobischof approved these changes

2021-07-20 13:47 UTC, merged