docs: added setup options to docs
caos/zitadel pull request #2127
Opened 2021-08-05 13:37 UTC by stebenz

2021-08-05 15:10 UTC, mffap requested changes
Looks very good and easy to understand! 
Some questions and suggestions.

2021-08-05 15:10 UTC, mffap commented on docs/docs/concepts/setup.md
> +            <li>Possibility to run ORBOS with one of the implemented Providers</li>
```suggestion
            <li>Possibility to run ORBOS with one of the [implemented providers](https://github.com/caos/orbos/blob/master/docs/orbiter/providers.md)</li>
```

2021-08-05 15:10 UTC, mffap commented on docs/docs/concepts/setup.md
> +            <li>Setup of Kubernetes cluster with ORBOS</li>
```suggestion
            <li>Setup of Kubernetes cluster with [ORBOS](https://github.com/caos/orbos)</li>
```

2021-08-05 15:10 UTC, mffap commented on docs/docs/concepts/setup.md
> +            <li>Environment to test and check should not be in productive use</li>
```suggestion
            <li>Environment to test and check (should not be in productive use)</li>
```

2021-08-05 15:10 UTC, mffap commented on docs/docs/concepts/setup.md
> +            <li>Access to used configuration</li>
Additionally maybe?

- Access to monitoring
- Access to relevant system and application logs

2021-08-05 15:10 UTC, mffap commented on docs/docs/concepts/setup.md
> +            <li>Access to the Kubernetes cluster or physical/virtual nodes</li>
```suggestion
            <li>Access to relevant Kubernetes cluster or physical/virtual nodes</li>
```

2021-08-05 15:10 UTC, mffap commented on docs/docs/concepts/setup.md
> +            <li>Access to the Kubernetes cluster or physical/virtual nodes</li>
Additionally: Do you need access to asset storage, backup storage, maybe database cluster/node?

2021-08-05 16:46 UTC, mffap submitted a review, later dismissed

2021-08-06 08:56 UTC, fforootd commented on docs/sidebars.js
> +          label: 'Setup by CAOS',
```suggestion
          label: 'CAOS Service Packages',
```

2021-08-06 08:56 UTC, fforootd commented on docs/docs/guides/installation/setup-orbos.md
> +title: ORBOS and ZITADEL setup by CAOS
```suggestion
title: ZITADEL setup with ORBOS
```

2021-08-06 08:56 UTC, fforootd commented on docs/docs/guides/installation/setup.md
> +title: ZITADEL setup by CAOS
```suggestion
title: ZITADEL setup
```

2021-08-20 11:50 UTC, mffap approved these changes

2021-08-20 11:50 UTC, merged