docs: restructure and add more content
caos/zitadel pull request #2232
Opened 2021-08-19 14:24 UTC by fgerschwiler

2021-08-25 11:22 UTC, fforootd commented
@fgerschwiler I think the concepts/policies and concepts/managers sections would be better located under guides

2021-08-25 11:30 UTC, mffap commented
> @fgerschwiler I think the concepts/policies and concepts/managers sections would be better located under guides

I think it makes sense to have them here. In understand the logic, as these are all ZITADEL specifc or general concepts required to understand the system or guides.

The form is not there yet, but I would keep them separated from the guides.

2021-08-25 11:32 UTC, mffap commented
@fgerschwiler it would be good to update the introduction to concepts and explain that section.

Also there is a typo ("twoo") and the "active work and subject to change" should be removed, we are beyond that now.

2021-08-25 11:32 UTC, fforootd reviewed
> The form is not there yet, but I would keep them separated from the guides.

ok I can live with that, but at first it felt a little counterintuitive 😁

2021-08-25 11:32 UTC, fforootd commented on docs/docs/apis/openidoauth/endpoints.md
> +The authorization_endpoint is the starting point for all initial user authentications. The user agent (browser) will be redirected to this endpoint to
```suggestion
The authorization_endpoint is the starting point for all initial user initiated requests. The user agent (browser) will be redirected to this endpoint to
```

2021-08-25 11:32 UTC, fforootd commented on docs/docs/apis/openidoauth/endpoints.md
> +see PKCE guide for more information
Can we provide a link here?

2021-08-25 11:34 UTC, mffap commented
> > The form is not there yet, but I would keep them separated from the guides.
> 
> ok I can live with that, but at first it felt a little counterintuitive 😁

I believe it's also due to a lack of content atm.

2021-08-25 11:52 UTC, mffap commented
@fgerschwiler @livio-a maybe we should stick to 'active voice' and directly addressed to the reader.

Example: "These projects should be created in ..." >> "Create these projects in ..."
or: "To give a customer permissions to a project, a project grant to the customer is need." >> "You need to grant a project to a customer to give the customer permission to use your project"

2021-08-25 12:02 UTC, mffap requested changes

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/policies.md
> +Each policy can be overridden and resetted to the default.
```suggestion
Each policy can be overridden and reset to the default.
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/policies.md
> +The following properties are possible:
```suggestion
The following settings are available:
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/policies.md
> +Define when a user should be locked.
```suggestion
Define when an account should be locked.
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/policies.md
> +- Maximum Password Attempts: When the user has reached the maximum password attempts the user will be locked
```suggestion
- Maximum Password Attempts: When the user has reached the maximum password attempts the account will be locked
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/policies.md
> +If a user is locked, an administrator has to unlock it in the ZITADEL console
```suggestion
If an account is locked, the administrator has to unlock it in the ZITADEL console
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/usecases/saas.md
> +To illustrate it a fictional organization and project is taken.
```suggestion
To illustrate it, a fictional organization and project is used.
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/usecases/saas.md
> +An organization is the top level in ZITADEL.
```suggestion
An organization is the ZITADEL resource which contains users, projects, applications, policies and so on. 
```

IMO the `system` is the top level 😁

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/usecases/saas.md
> +1. Your customer already owns an organization ZITADEL
```suggestion
1. Your customer already owns an organization in ZITADEL
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/usecases/saas.md
> +Subscriptions are organization based. This means, that each organization can choose her own tier based on the needed features.
```suggestion
Subscriptions are organization based. This means, that each organization can choose their own tier based on the needed features.
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/usecases/saas.md
> +In our use case we would have two different projects, for each environment one. So lets call it "Time Dev" and "Time Prod".
```suggestion
In this use case we would have two different projects, for each environment one. So lets call it "Time Dev" and "Time Prod".
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/usecases/saas.md
> +These projects should be created in "The Timing Company" organization, because this is the owner of the project.
```suggestion
These projects should be created in "The Timing Company" organization, because it is the owner of the project.
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/usecases/saas.md
> +To give a customer permissions to a project, a project grant to the customer is needed (search the granted organization by its domain).
```suggestion
To give a customer permissions to a project, a project grant to the customers organization is needed (search the granted organization by its domain).
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/usecases/saas.md
> +It is also possible to delegate only specific roles of the project to a customer.
```suggestion
It is also possible to delegate only specific roles of the project to a certain customer.
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/concepts/usecases/saas.md
> +All organizations which own the project or got it granted are able to authorize users.
```suggestion
All organizations which own the project or received a grant are able to authorize users.
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/guides/authentication/login-users.md
> +>
```suggestion
<Tabs
    groupId="app-type"
    default="web"
    values={[
        {'label': 'Web Application', 'value': 'web'},
        {'label': 'Native Application', 'value': 'native'},
        {'label': 'Single Page Application', 'value': 'spa'},
    ]}
>
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/guides/customization/branding.md
> +title: Branding
```suggestion
title: Brand Customization
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/guides/customization/branding.md
> +ZITADEL offers various customisation options for your branding.
```suggestion
ZITADEL offers various customization options for your projects brand design. 
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/guides/customization/branding.md
> +You are able to customize a light and a dark mode.
```suggestion
You are able to customize the light and a dark mode separately.
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/guides/customization/branding.md
> +All your settings will be removed and the default settings of the system will trigger.
```suggestion
### 2. Setting on your Project
Set the private labeling setting on your project to define which branding should trigger.

## Reset to default
If you don't like your customization anymore click the "reset policy" button.
All your settings will be removed and the default settings of the system will trigger.
```

2021-08-25 15:56 UTC, fforootd commented on docs/docs/guides/customization/texts.md
> +You are able to customize some of the texts in ZITADEL.
```suggestion
You are able to customize the texts used from ZITADEL.
```

2021-09-07 19:18 UTC, fforootd commented
@fgerschwiler is this ready to merge or does this still need work?

2021-09-08 06:15 UTC, fgerschwiler commented
> @fgerschwiler is this ready to merge or does this still need work?

I changed my feedback, but I am waiting for @livio-a to have a look at the his parts. Also we are not sure if we should change the feedback of panne about the tabs.

2021-09-08 06:52 UTC, fforootd commented
> I changed my feedback, but I am waiting for @livio-a to have a look at the his parts. Also we are not sure if we should change the feedback of panne about the tabs.

I think we should change the table for now to see how it works out. We might switch it back if people don't understand 😁

2021-09-22 13:37 UTC, livio-a submitted a review, later dismissed

2021-09-22 18:13 UTC, livio-a approved these changes

2021-09-23 08:33 UTC, mffap approved these changes

2021-09-23 08:34 UTC, merged