feat: Features query
caos/zitadel pull request #2610
Opened 2021-11-03 10:58 UTC by fgerschwiler

2021-11-04 07:26 UTC, livio-a submitted a review, later dismissed

2021-11-17 20:05 UTC, adlerhurst requested changes

2021-11-18 12:41 UTC, livio-a commented on internal/query/projection/feature_test.go
> +								false,
yes, but reduceFeatureSet will always set it

2021-11-18 12:49 UTC, livio-a commented on internal/authz/repository/eventsourcing/eventstore/token_verifier.go
> +	features, err := repo.Query.FeatureByOrgID(ctx, orgID)
oh yes, you're right

2021-11-18 12:50 UTC, livio-a commented on internal/authz/repository/eventsourcing/eventstore/token_verifier.go
> +	features, err := repo.Query.DefaultFeature(ctx)
i'll add all the missing `s`

2021-11-21 17:18 UTC, adlerhurst commented on internal/query/features_test.go
> +						604800000000000,
```suggestion
						7 * 24 * time.Hour,
```

2021-11-21 17:18 UTC, adlerhurst commented on internal/query/features_test.go
> +						604800000000000,
```suggestion
						7 * 24 * time.Hour,
```

2021-11-21 18:47 UTC, adlerhurst approved these changes

2021-11-21 19:22 UTC, merged