Text query
caos/zitadel pull request #2735
Opened 2021-11-24 07:56 UTC by fgerschwiler

2021-11-29 09:11 UTC, livio-a requested changes
please add tests for queries

2021-11-29 09:11 UTC, livio-a commented on internal/query/message_text.go
> +	}
reading from file is exactly the same as above, maybe put it in a separate func

2021-11-29 09:11 UTC, livio-a commented on internal/query/message_text.go
> +}
?

2021-11-29 09:11 UTC, livio-a commented on internal/query/mail_template.go
> +	}
please add table to columns

2021-11-29 12:39 UTC, fgerschwiler commented on internal/query/message_text.go
> +}
Bot used

2021-11-30 07:06 UTC, livio-a requested changes
could you please merge in `main` and there are some fields which could be null but this is not handled

2021-12-16 14:21 UTC, livio-a approved these changes

2021-12-16 14:21 UTC, merged