docs: update angular quickstart
caos/zitadel pull request #3025
Opened 2022-01-18 08:30 UTC by eliobischof

2022-01-18 14:37 UTC, peintnermax requested changes

2022-01-18 14:37 UTC, peintnermax commented on docs/docs/quickstarts/login/angular.md
> +Add the Auth module to your Angular imports in AppModule and provide the AuthConfig the providers section. Also ensure you have importe the HTTPClientModule.
```suggestion
Add the Auth module to your Angular imports in AppModule and provide the AuthConfig in the providers section. Also ensure to have imported the HTTPClientModule.
```

2022-01-20 07:53 UTC, eliobischof commented
@peintnermax plz re-review, thx

2022-01-20 09:13 UTC, peintnermax approved these changes

2022-01-20 09:13 UTC, merged