feat: OIDC config
caos/zitadel pull request #3245
Opened 2022-02-22 09:12 UTC by fgerschwiler

2022-02-22 14:12 UTC, adlerhurst requested changes

2022-02-22 14:12 UTC, adlerhurst commented on proto/zitadel/settings.proto
> +message OIDCConfig {
I think having the same object name for different use cases is a bad idea. My best alternative name by now is `OIDCSettings`

2022-02-23 12:06 UTC, fgerschwiler commented on internal/command/iam_oidc_config.go
> +	oidcSettingWriteModel, err := c.getOIDCConfig(ctx)
yes, ans also the file should be renamed, as well as the model

2022-02-25 15:02 UTC, adlerhurst approved these changes

2022-02-25 15:05 UTC, merged