docs: edits to guide section
caos/zitadel pull request #3247
Opened 2022-02-23 15:37 UTC by MattDodsonEnglish

This PR makes some major line edits to the "guides" section of the docs. In a few cases, I've added intros, or rewritten them to create a better flow between paragraphs and pages.

Some common edits are:
* Using bold for UI elements, italics for special terms, and monospace for variables and code
* rewriting passive tense into active tense
* breaking paragraphs up into distinct ideas, and using lists for instructions (following guidelines here: https://docs.microsoft.com/en-us/style-guide/scannable-content/)

2022-03-01 14:55 UTC, eliobischof requested changes

2022-03-01 14:55 UTC, eliobischof commented on docs/docs/guides/solution-scenarios/introduction.mdx
> +This guide outlines the real-world concepts you need to think about when implementing an Access Management System.
```suggestion
This guide outlines the real-world concepts you need to think about when integrating an Access Management System.
```

2022-03-01 14:55 UTC, eliobischof commented on docs/docs/guides/trainings/supportservice/recurring.md
> +We recommend an one day of training per support staff.
```suggestion
We recommend one day of training per support staff.
```

2022-03-01 15:51 UTC, fgerschwiler commented on docs/docs/guides/basics/organizations.mdx
> +Note that domain verification also removes the loginname from all users, some of whom might have used this combination in the global organization
yes

2022-03-01 15:53 UTC, fgerschwiler commented on docs/docs/guides/authorization/oauth-recommended-flows.md
> +For cases where the default flow is not feasible.
at the moment we have only documented the recommended flows, some alternatives are not documented so the module will not redirect

2022-03-01 15:59 UTC, eliobischof commented on docs/docs/guides/authorization/oauth-recommended-flows.md
> +For cases where the default flow is not feasible.
```suggestion
```

2022-03-01 16:07 UTC, eliobischof commented on docs/docs/guides/solution-scenarios/b2b.mdx
> +- Administrators: users who can grant additional organizations or departments and elect supervisors.
> yes, but it sounds a little bit complicated to me

LOL, to me too :-)

2022-03-01 16:15 UTC, eliobischof commented on docs/docs/guides/solution-scenarios/b2b.mdx
> +- Administrators: users who can grant additional organizations or departments and elect supervisors.
@juergrinaldi do you have an idea about how to simplify and/or illustrate the description for these groups and their capabilities?

2022-03-23 07:35 UTC, eliobischof approved these changes

2022-03-23 07:45 UTC, merged