feat: service accounts
caos/zitadel pull request #470
Opened 2020-07-14 15:52 UTC by adlerhurst

2020-08-25 07:01 UTC, fgerschwiler reviewed
add tests, in my opinion admin part should be finished with this pr, auth is possible on other pr, in this case keys and views should be included here

2020-08-25 07:01 UTC, fgerschwiler commented on pkg/grpc/management/proto/management.proto
> +  string preferred_login_name = 27;//
//?

2020-08-25 07:08 UTC, livio-a requested changes
same as Fabi... add some specific tests for human and machine (as wrong input)

2020-08-25 07:08 UTC, livio-a commented on migrations/cockroach/V1.99__user_machine.sql
> +--TODO: (management)project_members
TODO

2020-08-25 07:08 UTC, livio-a commented on pkg/grpc/management/proto/management.proto
> +// }
?

2020-08-25 07:08 UTC, livio-a commented on pkg/grpc/management/proto/management.proto
> +// full key
?

2020-08-25 07:08 UTC, livio-a commented on pkg/grpc/management/proto/management.proto
> +// }
?

2020-08-25 08:10 UTC, adlerhurst commented on internal/auth/repository/eventsourcing/handler/user.go
> +		es_model.HumanAdded:
done

2020-08-25 08:14 UTC, adlerhurst commented on internal/auth/repository/eventsourcing/handler/user.go
> +		es_model.MachineChanged,
done

2020-08-25 08:35 UTC, adlerhurst commented on internal/management/repository/eventsourcing/eventstore/user.go
> +	if user.HumanView == nil {
handeled in get<subobject>

2020-08-25 08:35 UTC, adlerhurst commented on internal/management/repository/eventsourcing/handler/user.go
> +		es_model.HumanAdded:
done

2020-08-25 08:40 UTC, adlerhurst commented on pkg/grpc/management/proto/management.proto
> +message UserEmailView { //equal
removed

2020-08-25 08:40 UTC, adlerhurst commented on pkg/grpc/management/proto/management.proto
> +  string preferred_login_name = 27;//
removed

2020-08-31 13:16 UTC, adlerhurst commented on internal/api/grpc/management/user_machine_converter.go
> +		Type:           management.MachineKeyType_MACHINEKEY_UNSPECIFIED, //TODO: type mapping
done

2020-08-31 13:16 UTC, adlerhurst commented on internal/management/repository/eventsourcing/handler/project_grant_member.go
> +//TODO: specific for user data
removed

2020-08-31 13:16 UTC, adlerhurst commented on internal/management/repository/eventsourcing/handler/project_member.go
> +//TODO: secific for user data
removed

2020-08-31 13:16 UTC, adlerhurst commented on internal/management/repository/eventsourcing/handler/user_grant.go
> +//TODO: secific for human or machine
removed

2020-08-31 13:16 UTC, adlerhurst commented on internal/user/repository/eventsourcing/eventstore.go
> +	if existing.Human == nil {
done

2020-08-31 13:16 UTC, adlerhurst commented on internal/user/repository/eventsourcing/eventstore.go
> +	if existing.Human == nil {
done

2020-08-31 13:17 UTC, adlerhurst commented on internal/user/repository/eventsourcing/eventstore.go
> +	if existing.Human == nil {
done

2020-08-31 13:17 UTC, adlerhurst commented on internal/user/repository/eventsourcing/model/mfa.go
> +func (u *Human) appendOtpAddedEvent(event *es_models.Event) error {
done

2020-08-31 13:17 UTC, adlerhurst commented on migrations/cockroach/V1.99__user_machine.sql
> +--TODO: (management)project_members
migration 1.10 is final edition

2020-08-31 13:17 UTC, adlerhurst commented on internal/admin/repository/eventsourcing/handler/iam_member.go
> +//TODO: specific for user data
removed

2020-08-31 13:17 UTC, adlerhurst commented on internal/api/grpc/management/user_machine_converter.go
> +		Type:           management.MachineKeyType_MACHINEKEY_UNSPECIFIED, //TODO: type mapping
removed

2020-08-31 13:18 UTC, adlerhurst commented on internal/auth/repository/eventsourcing/handler/user_grant.go
> +//TODO: specific for user data
done

2020-08-31 13:18 UTC, adlerhurst commented on internal/management/repository/eventsourcing/handler/project_grant_member.go
> +//TODO: specific for user data
done

2020-08-31 13:18 UTC, adlerhurst commented on internal/management/repository/eventsourcing/handler/project_member.go
> +//TODO: secific for user data
done

2020-08-31 13:18 UTC, adlerhurst commented on internal/management/repository/eventsourcing/handler/user_grant.go
> +//TODO: secific for human or machine
don

2020-08-31 13:18 UTC, adlerhurst commented on internal/user/repository/eventsourcing/model/user_machine.go
> +		logging.Log("MODEL-iBgOc").Panic("key unimplemented")
implemented

2020-08-31 13:18 UTC, adlerhurst commented on internal/user/repository/view/model/user.go
> +			//TODO: keys
done

2020-08-31 13:19 UTC, adlerhurst commented on migrations/cockroach/V1.99__user_machine.sql
> +--TODO: (management)project_members
migration 1.10 is final edition

2020-08-31 13:19 UTC, adlerhurst commented on pkg/grpc/management/proto/management.proto
> +// }
done

2020-08-31 13:19 UTC, adlerhurst commented on pkg/grpc/management/proto/management.proto
> +// full key
implemented

2020-08-31 13:19 UTC, adlerhurst commented on pkg/grpc/management/proto/management.proto
> +// }
implemented

2020-08-31 15:32 UTC, fgerschwiler approved these changes

2020-08-31 15:46 UTC, livio-a approved these changes

2020-08-31 15:48 UTC, merged