feat: Identity brokering
caos/zitadel pull request #730
Opened 2020-09-11 12:21 UTC by fgerschwiler

2020-09-17 12:26 UTC, fgerschwiler commented on internal/api/grpc/admin/idp_config_converter.go
> +			UsernameMapping:       oidcMappingFieldToModel(idp.IdpDisplayNameMapping),
in my opinion its ok like this, because it should be private

2020-09-18 06:54 UTC, livio-a requested changes

2020-09-18 06:54 UTC, livio-a commented on internal/auth/repository/eventsourcing/eventstore/user.go
> +	user, aggregates, err := repo.UserEvents.PrepareRegisterUser(ctx, registerUser, nil, pwPolicy, orgPolicy, resourceOwner)
Register and RegisterExternalUser do exactly the same thing with the difference of Register not taking ExternalIDP as param... i'd expose Register as separate func and either call RegisterExternalUser with externalIDP set to nil or create a private func with both of them use

2020-09-18 06:54 UTC, livio-a commented on internal/user/repository/eventsourcing/eventstore.go
> +	existingUser, err := es.UserByID(ctx, externalIDPs[0].AggregateID)
using the id on first index might lead to problems as the function name `BulkAddExternalIDPs` does not make it clear that it must only be use on a single Aggregate

2020-09-18 06:54 UTC, livio-a commented on internal/user/repository/eventsourcing/user.go
> +func changeUniqueUserNameAggregate(ctx context.Context, aggCreator *es_models.AggregateCreator, resourceOwner, userID, oldUsername, username string, userLoginMustBeDomain bool) ([]*es_models.Aggregat
added `userID` param is never used

2020-09-18 11:26 UTC, livio-a approved these changes

2020-09-18 11:26 UTC, merged

2020-09-18 11:36 UTC, fforootd commented
:tada: This PR is included in version 0.87.0 :tada:

The release is available on:
- [GitHub release](https://github.com/caos/zitadel/releases/tag/v0.87.0)
- `v0.87.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: