feat: policies on aggregates
caos/zitadel pull request #799
Opened 2020-10-01 08:41 UTC by fgerschwiler

2020-10-13 07:04 UTC, fgerschwiler reviewed
I only checked console files, rest should be reviewed by livio

2020-10-13 07:04 UTC, fgerschwiler commented on console/src/app/modules/policies/password-age-policy/password-age-policy-routing.module.ts
> +    // },
Remove comments

2020-10-13 07:04 UTC, fgerschwiler commented on console/src/assets/environment.json
> +    "clientid": "77163028910563591@zitadel"
Maybe you should revert this? to always have dev on master

2020-10-14 14:43 UTC, adlerhurst requested changes

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/eventstore_test.go
> +			if !tt.res.wantErr && result.MaxAgeDays != tt.res.result.MaxAgeDays {
can panic

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/eventstore_test.go
> +			if !tt.res.wantErr && result.MaxAttempts != tt.res.result.MaxAttempts {
can panic

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/model/org_iam_policy.go
> +	o.OrgIamPolicy = new(iam_es_model.OrgIAMPolicy)
```suggestion
	o.OrgIAMPolicy = new(iam_es_model.OrgIAMPolicy)
```

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_age_policy_test.go
> +			for i := 0; i < tt.res.eventLen; i++ {
can panic

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_age_policy_test.go
> +			for i := 0; i < tt.res.eventLen; i++ {
can panic

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_age_policy_test.go
> +				if !tt.res.wantErr && agg.Events[i].Type != tt.res.eventTypes[i] {
can panic

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_complexity_policy_test.go
> +				if !tt.res.wantErr && agg.Events[i].Type != tt.res.eventTypes[i] {
can panic

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_complexity_policy_test.go
> +				if !tt.res.wantErr && agg.Events[i].Type != tt.res.eventTypes[i] {
can panic

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_complexity_policy_test.go
> +				if !tt.res.wantErr && agg.Events[i].Type != tt.res.eventTypes[i] {
can panic

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_lockout_policy_test.go
> +				if !tt.res.wantErr && agg.Events[i].Type != tt.res.eventTypes[i] {
can panic

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_lockout_policy_test.go
> +				if !tt.res.wantErr && agg.Events[i].Type != tt.res.eventTypes[i] {
can panic

2020-10-14 14:43 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_lockout_policy_test.go
> +				if !tt.res.wantErr && agg.Events[i].Type != tt.res.eventTypes[i] {
can panic

2020-10-14 14:55 UTC, fgerschwiler commented on internal/api/grpc/admin/org_converter.go
> +		OrgId:                 policy.AggregateID,
this is from proto

2020-10-15 07:06 UTC, adlerhurst requested changes

2020-10-15 07:06 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_age_policy_test.go
> +			if !tt.res.wantErr && len(agg.Events) != tt.res.eventLen {
remove `!tt.res.wantErr &&` in all tests because it's checked previously

2020-10-15 07:06 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_complexity_policy_test.go
> +			if !tt.res.wantErr && len(agg.Events) != tt.res.eventLen {
remove `!tt.res.wantErr &&` in all tests because it's checked previously

2020-10-15 07:06 UTC, adlerhurst commented on internal/org/repository/eventsourcing/password_lockout_policy_test.go
> +			if !tt.res.wantErr && len(agg.Events) != tt.res.eventLen {
remove `!tt.res.wantErr &&` in all tests because it's checked previously

2020-10-15 07:11 UTC, fgerschwiler reviewed
Console approved

2020-10-15 08:26 UTC, adlerhurst approved these changes

2020-10-15 08:27 UTC, merged

2020-10-15 08:41 UTC, fforootd commented
:tada: This PR is included in version 0.92.0 :tada:

The release is available on:
- [GitHub release](https://github.com/caos/zitadel/releases/tag/v0.92.0)
- `v0.92.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: