refactor: tracing from opencensus to opentelemetry
caos/zitadel pull request #937
Opened 2020-11-04 15:28 UTC by adlerhurst

2020-11-04 15:59 UTC, adlerhurst commented
@livio-a @fgerschwiler im not sure if it makes sense to provide the agent.yaml

2020-11-05 12:45 UTC, fgerschwiler approved these changes

2020-11-06 06:51 UTC, livio-a requested changes

2020-11-06 06:51 UTC, livio-a commented on internal/tracing/span.go
> +	s.span.SetAttributes(label.Uint32("grpc_code", uint32(code)), label.String("grpc_msg", msg))
isn't (error) id returned as well, which could be set as attribute as well?

2020-11-06 06:51 UTC, livio-a commented on cmd/zitadel/startup.yaml
> +    Endpoint: localhost:9096
please use a env var for this

2020-11-06 06:54 UTC, livio-a commented
> @livio-a @fgerschwiler im not sure if it makes sense to provide the agent.yaml

i'm not sure either... especially as it's proprietary to the service we use (and including the use of our key store)

2020-11-20 06:49 UTC, livio-a approved these changes
we might have to move the content of agent.yaml into the docs later

2020-11-20 06:57 UTC, merged

2020-11-20 07:10 UTC, fforootd commented
:tada: This PR is included in version 0.104.9 :tada:

The release is available on [GitHub release](https://github.com/caos/zitadel/releases/tag/v0.104.9)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: