docs: review docs
caos/zitadel pull request #944
Opened 2020-11-06 13:58 UTC by mffap

2020-11-29 15:43 UTC, mffap commented
@fforootd  a mix of smaller changes to the docs. Also corrected the title heading for management roles.

2020-11-29 21:24 UTC, fforootd requested changes

2020-11-29 21:24 UTC, fforootd commented on site/docs/administrate/02-organisations.en.md
> +[//]: # (@fforootd screenshot sais "projects" - bit confusing)
Managers can be "managed" on the IAM resouces e.g projects

2020-11-29 21:24 UTC, fforootd commented on site/docs/administrate/02-organisations.en.md
> +[//]: # (@fforootd Is a "Manager" another "Organisation owner", or is this a special role?)
Org. Owner is a Manager Role 

Generally all IAM roles are Manager Roles

2020-11-29 21:24 UTC, fforootd commented on site/docs/administrate/03-projects.en.md
> +The owner of a project can grant (some would say "delegate") certain roles or all roles to another organisation. The target organisaton can then indipendently manage the assignment of their users to
```suggestion
The owner of a project can grant (some would say "delegate") certain roles or all roles to another organisation. The target organization can then indipendently manage the assignment of their users to  the role within the [granted project](administrate#Project_vs_granted_Project).
```

2020-11-29 21:24 UTC, fforootd commented on site/docs/administrate/07-policies.en.md
> +This policy enforces passwords of users within the organisation to be compliant.
```suggestion
This policy enforces passwords of users within the organization to be compliant.
```

2020-11-29 21:24 UTC, fforootd commented on site/docs/start/00-quick-start.en.md
> +Hi there,
Is this by design 😁

2020-11-29 21:26 UTC, fforootd commented on site/docs/administrate/02-organisations.en.md
> +</details>
@peintnermax will those work?

2020-12-01 15:55 UTC, fforootd approved these changes

2020-12-01 15:56 UTC, merged

2020-12-02 08:06 UTC, fforootd commented
:tada: This PR is included in version 0.107.0 :tada:

The release is available on [GitHub release](https://github.com/caos/zitadel/releases/tag/v0.107.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: